on:
  workflow_call:
    inputs:
      appName:
        description: 'github-action-cicd-demo'
        required: true
        type: string
      appVersion:
        description: 1.0.0
        required: false
        type: string  
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current  repo
      uses: actions/checkout@v4
    - name : Checkout template repo
      uses: actions/checkout@v4
      with:
        repository: 'durgeshnttdata/workflow-template'
        path: 'settings' 
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Test with Maven
      env:
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn test -s settings/settings.xml
      
  build_deploy_dev :
    runs-on: ubuntu-latest
    needs: test
    environment: ${{vars.ENV}} 
    steps:
      - name: Checkout current  repo
        uses: actions/checkout@v4
    
      - name : Checkout template repo
        uses: actions/checkout@v4
        with:
          repository: 'durgeshnttdata/workflow-template'
          path: 'settings'
    
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
    
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
    
      - name: Build  and Publish to Exchange
        run: mvn -s settings/settings.xml clean deploy -DskipTests -DCLIENT_ID=${{ secrets.CONNECTED_APP_CLIENT_ID }} -DCLIENT_SECRET=${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: target/*.jar
    
      - name : Download artifact
        uses: actions/download-artifact@master
        with:
          name: artifacts
    
      - name: Deploy to Runtime Environment
        run : |
          artifactName=$(ls *.jar | head -1)
          mvn  mule:deploy -Dmule.artifact=$artifactName -s settings/settings.xml -DskipTests -DmuleDeploy -Dcloudhub.environment=${{ secrets.ANYPOINT_ENVIRONMENT }} -Dapplication.name=${{ inputs.appName }}-dev -Denv=${{vars.ENV}} -Dcloudhub.target=${{vars.TARGET}} -DCLIENT_ID=${{ secrets.CONNECTED_APP_CLIENT_ID }} -DCLIENT_SECRET=${{ secrets.CONNECTED_APP_CLIENT_SECRET }} -Danypoint.platform.client_id=${{ secrets.ANYPOINT_CLIENT_ID}} -Danypoint.platform.client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }}
