on:
  workflow_call:
    inputs:
      appName:
        description: 'github-action-cicd-demo'
        required: true
        type: string
      appVersion:
        description: 1.0.0
        required: true
        type: string  
jobs:                 
  deploy_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout current  repo 
        uses: actions/checkout@v4 
      - name : Checkout template repo
        uses: actions/checkout@v4
        with:
          repository: 'durgeshnttdata/workflow-template'
          path: 'settings'
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      
      - name: Deploy to Runtime Environment
        run: |
            artifactName=$(ls *.jar | head -1)
            mvn  mule:deploy -Dmule.artifact=$artifactName -s settings/settings.xml -DskipTests -DmuleDeploy -Dcloudhub.environment=${{ secrets.ANYPOINT_ENVIRONMENT }} -Dapplication.name=${{ inputs.appName }}-test -DskipTests -Dcloudhub.target=${{vars.TARGET}} -DCLIENT_ID=${{ secrets.CONNECTED_APP_CLIENT_ID }} -DCLIENT_SECRET=${{ secrets.CONNECTED_APP_CLIENT_SECRET }} -Danypoint.platform.client_id=${{ secrets.ANYPOINT_CLIENT_ID}} -Danypoint.platform.client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }}
